### ISSUE TITLE
Feel free to add resources.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Cybros/Lecture-Series-1-HTML-CSS-JS#1]
Feel free to add more resources if you find any.

**Comment by rbhatia46** [comment]
Added a small JS Project called MemoryGame to Cybros Repository's, this can be a mini project demonstrating all basic concepts of JS.

**Comment by divyanshu-rawat** [comment]
@rbhatia46  sorry to say I have removed the project please add it inside the Lecture-Series-1-HTML-CSS-JS. Don't add any project on the front page of org.
Create a Folder Projects Inside Lecture-Series-1-HTML-CSS-JS repo. and push memory game inside it.
